[versions]
lombok = "1.18.42"
paper = "1.21.8-R0.1-SNAPSHOT"

shadow = "9.2.2"
run-paper = "3.0.2"

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }